#!/usr/bin/env bun
// 01 Compete
// ----------
// Axis: Compete -- many solutions, one problem.
//
// Four competitors (three profiles of the worker model: minimal-diff,
// best-practices, performance; plus one frontier model) each propose a full
// patch to src/fixtures/readiness.ts as a ToolLoopAgent with structured
// output (Output.object). Every candidate runs concurrently with
// Promise.allSettled and a shared deadline abortSignal.
//
// Judging is two-stage, and the judge never writes its own rubric:
//   1. Deterministic: run the candidate against the fixed fixture test suite
//      in a sandboxed child process (src/lib/sandbox.ts). Candidates that
//      fail any test are eliminated before any judge call happens.
//   2. LLM rubric: survivors are scored by gpt-5.4-nano against the human
//      rubric in src/fixtures/rubric.md (src/lib/judge.ts). The rubric text
//      is never generated by the judge itself.
//
// Every worker gets exactly one span (src/lib/otel.ts) carrying profile,
// costUsd, latencyMs, outcome, whyItExisted. --budget-usd / --deadline-ms
// cap the whole tournament; a shared AbortSignal cancels remaining
// generations once the deadline passes, and the table still prints whatever
// finished.
import { ToolLoopAgent, Output, isStepCount } from "ai";
import { z } from "zod";
import { competitorProfiles, type CompetitorProfile } from "../lib/profiles";
import { withWorkerSpan, dumpWorkerSpans, initTelemetry } from "../lib/otel";
import { costUsd, formatUsd } from "../lib/prices";
import { runSandbox, type SandboxResult } from "../lib/sandbox";
import { judgeCandidate, type RubricJudgeResult } from "../lib/judge";
import { parseCaps, deadlineSignal } from "../lib/cli";
import { printTable, printKV, heading } from "../lib/print";

const patchSchema = z.object({
  source: z.string().describe("The complete new contents of readiness.ts"),
  explanation: z.string().describe("One paragraph explaining the fix"),
});

export interface CandidateResult {
  profile: string;
  modelId: string;
  generated: boolean;
  costUsd: number;
  latencyMs: number;
  outcome: string;
  source?: string;
  sandbox?: SandboxResult;
  rubric?: RubricJudgeResult;
  error?: string;
}

/** Run one competitor: generate a patch, then sandbox-test it. Wrapped in one worker span. */
async function runCompetitor(
  profile: CompetitorProfile,
  signal: AbortSignal,
): Promise<CandidateResult> {
  // `telemetry` is an agent-construction setting, not a per-call generate()
  // option (ToolLoopAgent.generate only accepts CALL_OPTIONS + lifecycle
  // callbacks + abortSignal/timeout) -- PLAN.md assumed the generateText
  // shape where telemetry rides the call. Setting functionId here still
  // gives each profile's own ai.generateText span a distinct name.
  const agent = new ToolLoopAgent({
    model: profile.model,
    instructions: profile.instructions,
    output: Output.object({ schema: patchSchema }),
    stopWhen: isStepCount(2),
    telemetry: { functionId: `compete-${profile.name}` },
  });

  try {
    return await withWorkerSpan(
      { profile: profile.name, whyItExisted: `compete: ${profile.name} proposes a patch to readiness.ts` },
      async () => {
        const start = Date.now();
        const result = await agent.generate({
          prompt: "Patch readiness.ts to fix the three bugs described in your instructions.",
          abortSignal: signal,
        });
        const latencyMs = Date.now() - start;
        const spend = costUsd(profile.modelId, result.usage);
        const sandbox = await runSandbox(result.output.source, 8000);
        const outcome = sandbox.ok ? "passed-sandbox" : `failed-sandbox(${sandbox.passed}/${sandbox.total})`;
        return {
          result: {
            profile: profile.name,
            modelId: profile.modelId,
            generated: true,
            costUsd: spend,
            latencyMs,
            outcome,
            source: result.output.source,
            sandbox,
          } satisfies CandidateResult,
          costUsd: spend,
          latencyMs,
          outcome,
        };
      },
    );
  } catch (err) {
    const aborted = signal.aborted;
    return {
      profile: profile.name,
      modelId: profile.modelId,
      generated: false,
      costUsd: 0,
      latencyMs: 0,
      outcome: aborted ? "cancelled(deadline)" : "error",
      error: (err as Error).message.slice(0, 200),
    };
  }
}

async function main() {
  const { budgetUsd, deadlineMs } = parseCaps(process.argv.slice(2), { budgetUsd: 0.3, deadlineMs: 60_000 });
  initTelemetry();
  heading("01 Compete — four competitors, sandboxed tests, LLM rubric judge");
  printKV("caps", { budgetUsd, deadlineMs });

  const signal = deadlineSignal(deadlineMs);
  const profiles = competitorProfiles();

  const settled = await Promise.allSettled(profiles.map((p) => runCompetitor(p, signal)));
  const candidates: CandidateResult[] = settled.map((s, i) =>
    s.status === "fulfilled"
      ? s.value
      : {
          profile: profiles[i]!.name,
          modelId: profiles[i]!.modelId,
          generated: false,
          costUsd: 0,
          latencyMs: 0,
          outcome: "rejected",
          error: String(s.reason).slice(0, 200),
        },
  );

  let totalCostUsd = candidates.reduce((sum, c) => sum + c.costUsd, 0);

  // Stage 2: only sandbox survivors go to the LLM rubric judge.
  const survivors = candidates.filter((c) => c.sandbox?.ok && c.source);
  for (const c of survivors) {
    if (totalCostUsd >= budgetUsd) {
      c.outcome += "; judge-skipped(budget)";
      continue;
    }
    try {
      const rubric = await judgeCandidate(c.profile, c.source!, { abortSignal: signal });
      c.rubric = rubric;
      totalCostUsd += rubric.costUsd;
    } catch (err) {
      c.outcome += `; judge-error(${(err as Error).message.slice(0, 40)})`;
    }
  }

  const rows = candidates.map((c) => ({
    profile: c.profile,
    model: c.modelId,
    sandbox: c.sandbox ? `${c.sandbox.passed}/${c.sandbox.total}` : "-",
    rubricScore: c.rubric?.score.total,
    disqualified: c.rubric?.score.disqualified ?? false,
    costUsd: c.costUsd + (c.rubric?.costUsd ?? 0),
    latencyMs: c.latencyMs,
    outcome: c.outcome,
  }));
  printTable("candidates", rows);

  const winner = survivors
    .filter((c) => c.rubric && !c.rubric.score.disqualified)
    .sort((a, b) => (b.rubric!.score.total ?? 0) - (a.rubric!.score.total ?? 0))[0];

  printKV("result", {
    winner: winner ? `${winner.profile} (${winner.modelId})` : "none (no candidate passed the sandbox and rubric)",
    winnerScore: winner?.rubric?.score.total,
    totalCostUsd: formatUsd(totalCostUsd),
    budgetUsd: formatUsd(budgetUsd),
    stopReason: totalCostUsd >= budgetUsd ? "budget reached" : signal.aborted ? "deadline reached" : "all candidates evaluated",
  });

  const { exporter } = initTelemetry();
  printTable("worker spans", dumpWorkerSpans(exporter));
}

main().catch((err) => {
  console.error("01-compete failed:", err);
  process.exitCode = 1;
});
