import { readFile } from 'node:fs/promises'
import { z } from 'zod'

export const POKEDEX_TOOLS = ['pokedex_list_resources', 'pokedex_list', 'pokedex_search', 'pokedex_get'] as const
export type PokedexToolName = (typeof POKEDEX_TOOLS)[number]
export const investigationRequestSchema = z.object({ runId: z.string().min(1), scenarioId: z.string().min(1), prompt: z.string().min(1), gatewayBaseUrl: loopbackUrlSchema(), deadlineMs: z.number().int().positive(), maxToolCalls: z.number().int().positive(), model: z.literal('openai/gpt-5.6-luna'), reasoningEffort: z.literal('none') })
export type InvestigationRequest = z.infer<typeof investigationRequestSchema>
export const answerSchema = z.object({ summary: z.string(), claims: z.array(z.object({ path: z.string().min(1), value: z.unknown(), requestIds: z.array(z.string()).min(1) })) })
export type InvestigationAnswer = z.infer<typeof answerSchema>
export interface ToolCallEvidence { tool: PokedexToolName; arguments: unknown; requestId: string; ok: boolean; latencyMs: number; disposition: 'gateway' | 'blocked'; error?: unknown }
export interface InvestigationEvidence { stack: 'mastra'; answer: InvestigationAnswer | null; toolCalls: ToolCallEvidence[]; usage: { inputTokens: number; outputTokens: number; reasoningTokens?: number }; latencyMs: number; stopReason: string; stopMetadata: { finishReason?: string; error?: string; toolCallAttempts: number; maxToolCalls: number; deadlineMs: number } }
export interface ToolDefinition { description: string; inputSchema: Record<string, unknown> }
export async function loadPokedexToolContract(): Promise<Record<PokedexToolName, ToolDefinition>> { const raw = JSON.parse(await readFile(new URL('../fixtures/pokedex-tools.schema.json', import.meta.url), 'utf8')) as Record<string, unknown>; const tools = raw.tools; const source = (Array.isArray(tools) ? Object.fromEntries(tools.map(item => [String((item as Record<string, unknown>).name), item])) : (tools ?? raw)) as Record<string, unknown>; const out = {} as Record<PokedexToolName, ToolDefinition>; for (const name of POKEDEX_TOOLS) { const item = source[name] as Record<string, unknown> | undefined; if (!item) throw new Error(`Pokédex contract is missing ${name}`); out[name] = { description: String(item.description ?? name), inputSchema: (item.inputSchema ?? item.parameters ?? { type: 'object', properties: {}, additionalProperties: false }) as Record<string, unknown> } } return out }
export class PokedexGatewaySession {
  readonly evidence: ToolCallEvidence[] = []; readonly signal: AbortSignal; #calls = 0; limitExceeded = false; #timer: ReturnType<typeof setTimeout>
  constructor(readonly request: InvestigationRequest) { const controller = new AbortController(); this.#timer = setTimeout(() => controller.abort(new Error('investigation deadline exceeded')), request.deadlineMs); this.signal = controller.signal }
  close(): void { clearTimeout(this.#timer) }
  async call(tool: PokedexToolName, args: unknown): Promise<unknown> { const started = Date.now(); if (++this.#calls > this.request.maxToolCalls) { this.limitExceeded = true; const error = { code: 'MAX_TOOL_CALLS', message: 'tool-call budget exhausted', retryable: false, retryAfterMs: null, requestId: `local-${this.request.runId}-${this.#calls}` }; this.evidence.push({ tool, arguments: args, requestId: error.requestId, ok: false, latencyMs: 0, disposition: 'blocked', error }); return error } try { const response = await fetch(`${this.request.gatewayBaseUrl.replace(/\/$/, '')}/tools/${tool}`, { method: 'POST', signal: this.signal, headers: { 'content-type': 'application/json', 'x-pokedex-run-id': this.request.runId, 'x-pokedex-scenario-id': this.request.scenarioId, 'x-pokedex-stack': 'mastra' }, body: JSON.stringify(args ?? {}) }); const body = await response.json() as Record<string, unknown>; const requestId = String(body.requestId ?? (body.error as Record<string, unknown> | undefined)?.requestId ?? response.headers.get('x-request-id') ?? `missing-${this.#calls}`); const ok = response.ok && body.ok !== false; this.evidence.push({ tool, arguments: args, requestId, ok, latencyMs: Date.now() - started, disposition: 'gateway', ...(ok ? {} : { error: body.error ?? body }) }); return body } catch (cause) { return this.#failure(tool, args, this.signal.aborted ? 'DEADLINE' : 'GATEWAY_UNAVAILABLE', cause instanceof Error ? cause.message : String(cause), !this.signal.aborted, started) } }
  #failure(tool: PokedexToolName, args: unknown, code: string, message: string, retryable: boolean, started: number): unknown { const error = { code, message, retryable, retryAfterMs: null, requestId: `local-${this.request.runId}-${this.#calls}` }; this.evidence.push({ tool, arguments: args, requestId: error.requestId, ok: false, latencyMs: Date.now() - started, disposition: 'gateway', error }); return error }
}
export function validateCitations(answer: InvestigationAnswer | null, calls: ToolCallEvidence[]): boolean { const ids = new Set(calls.filter(c => c.ok).map(c => c.requestId)); return Boolean(answer && answer.claims.every(c => c.requestIds.every(id => ids.has(id)))) }
function loopbackUrlSchema() { return z.string().url().superRefine((value, ctx) => { const url = new URL(value); if (url.protocol !== 'http:' || url.username || url.password || !['localhost', '127.0.0.1', '[::1]'].includes(url.hostname)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'gatewayBaseUrl must be credential-free HTTP on localhost, 127.0.0.1, or [::1]' }) }) }
